apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  data_source.yml: |
    # config file version
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-service:8080
    - name: Potty
      type: prometheus
      access: proxy
      url: http://potty-service:8080